### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by oldani** [aio-libs/aioredis#337]
Traceback:
```python

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in go
  File "/home/vagrant/.local/lib/python3.6/site-packages/aioredis/commands/__init__.py", line 146, in create_redis
    loop=loop)
  File "/home/vagrant/.local/lib/python3.6/site-packages/aioredis/connection.py", line 79, in create_connection
    address, ssl=ssl, loop=loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 128, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 236, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

Code:
```python
import asyncio
import aioredis

loop = asyncio.get_event_loop()

async def go():
    redis = await aioredis.create_redis(
        'redis://127.0.0.1:6379', loop=loop)
    # Also tested with localhost as on examples
    await redis.set('my-key', 'value')
    val = await redis.get('my-key')
    print(val)
    redis.close()
    await redis.wait_closed()
loop.run_until_complete(go())
```

Environments tested:
```
1- VM clean setup (Ubuntu 16.04 64bits/ Python3.6)
2- VM clean setup (Ubuntu 17.10 64bits/ Python3.6)
3- MacOS Sierra (10.12.6/Python 3.6.1)
```

**Comment by popravich** [comment]
aioredis version?

**Comment by popravich** [comment]
Must be `v1.0`

**Comment by oldani** [comment]
I tested with `0.3.5, 0.3.4 and 0.3.0`

**Comment by popravich** [comment]
Use v1.0! Redis URI is supported since v1.0 only!

**Comment by enugentdt** [comment]
I hate to reopen an old issue, but I'm having this error with v1.2.0 on an Alpine docker container. Is this a known issue, or possibly me messing something up?

**Comment by enugentdt** [comment]
Update: I found the issue. It was my environment variables.

To anybody ending up here, it's because the IP you entered is invalid.

Would it be possible to catch this or document it somehow, that the server couldn't be found instead of giving a cryptic error message?

**Comment by jppavez** [comment]
I fixed this problem adding the prefix "redis://" to the HOST IP.

For example:

redis://127.0.0.1
