### ISSUE TITLE
elastic cache connection refused error

### ISSUE THREAD

**Issue by balaa** [aio-libs/aioredis#429]
i tried  redis library im able to connect to rediscache without any issue but with aioredis im getting connection refused . 
import redis
r = redis.Redis('redis://XXX-XXX.XXX.XX.0001.use1.cache.amazonaws.com:6379')
print(r)
Redis<ConnectionPool<Connection<host=redis://XXX-XXX.XXX.XX.0001.use1.cache.amazonaws.com:6379,port=6379,db=0>>>

async def init_app():
    app = web.Application(debug=True)
    app.add_routes(routes)
    app['redis_pool'] = await aioredis.create_redis_pool(
        'redis://XXX-XXX.XXX.XX.0001.use1.cache.amazonaws.com:6379',
        minsize=5, maxsize=10, encoding='utf-8',
        loop=loop)
    return app
app = loop.run_until_complete(init_app())
if __name__ == "__main__":
    web.run_app(app)

the traceback is as follows:
Traceback (most recent call last):
  File "aiohttp_app.py", line 212, in <module>
    app = loop.run_until_complete(init_app())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "aiohttp_app.py", line 202, in init_app
    loop=loop)
  File "/home/ec2-user/batch_env/lib64/python3.7/site-packages/aioredis/commands/__init__.py", line 200, in create_redis_pool
    loop=loop)
  File "/home/ec2-user/batch_env/lib64/python3.7/site-packages/aioredis/pool.py", line 56, in create_pool
    await pool._fill_free(override_min=False)
  File "/home/ec2-user/batch_env/lib64/python3.7/site-packages/aioredis/pool.py", line 388, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/home/ec2-user/batch_env/lib64/python3.7/site-packages/aioredis/connection.py", line 107, in create_connection
    timeout, loop=loop)
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 384, in wait_for
    return await fut
  File "/home/ec2-user/batch_env/lib64/python3.7/site-packages/aioredis/stream.py", line 19, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 475, in sock_connect
    return await fut
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('X.X.X.X', 6379)

**Comment by balaa** [comment]
today I'm able to connect without any issue
