### ISSUE TITLE
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by yashrsharma44** [aio-libs/aioredis#434]
When I am running an example , given in the aioredis documentation, I am getting these sort of error - 
```
Traceback (most recent call last):
  File "python", line 26, in <module>
  File "python", line 7, in main
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address
```
I am running the above code without any proxy.

**Comment by NARESHSWAMI199** [comment]
i have installed redis  but same error
