### ISSUE TITLE
Error trying to import discord.py 1.0.0 right after installing it through pip.

### ISSUE THREAD

**Issue by Meinns** [aio-libs/aioredis#437]
It shows this error

`Traceback (most recent call last):
  File "D:\Pessoal\Animes\Discord\000.py", line 1, in <module>
    import discord
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 27, in <module>
    from .user import User, Profile
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\user.py", line 33, in <module>
    import discord.abc
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\abc.py", line 40, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\voice_client.py", line 58, in <module>
    from .gateway import *
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py", line 29, in <module>
    import websockets
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\client.py", line 20, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from .compatibility import asyncio_ensure_future
  File "C:\Users\Utilizador\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\compatibility.py", line 16
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax`

**Comment by webknjaz** [comment]
There's exactly zero references to aiohttp in that traceback. I assume that you need to find out the real project that you use and commute with them.
