### ISSUE TITLE
don't support custom command

### ISSUE THREAD

**Issue by dreambe** [aio-libs/aioredis#599]
aioredis      version   1.2.0
redis server   4.0
python 3.7.1

my code is:
```
import asyncio
import aioredis

async def run():
    pool = await aioredis.create_pool(
        'redis://xxx.xx.xx.xx, minsize=5, maxsize=10)
    print(await pool.execute('my_command',  'xxxxxx'))
    pool.close()
    await pool.wait_closed()
if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(run())
```

but when I change into this, it's work well:
```
import asyncio
import aioredis

async def connect_uri():
    conn = await aioredis.create_connection('redis://xxx.xx.xx.xx')
    print(await conn.execute('my_command',  'xxxxx'))
```

'my_command' is a custom command by my self via redis-protocol,
so, is aioredis support this? THX

worng message as below:

Traceback (most recent call last):
  File "ralogs_aio_test.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "ralogs_aio_test.py", line 6, in run
    'redis://xxx.xx.xx.xx', minsize=5, maxsize=10)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 56, in create_pool
    await pool._fill_free(override_min=False)
  File "/usr/local/lib/python3.7/site-packages/aioredis/pool.py", line 391, in _fill_free
    await conn.execute('ping')
aioredis.errors.ReplyError: WRONGTYPE Array of at least 2 Bulk String is required

**Comment by dreambe** [comment]
`data = await conn.execute('my_key', 'xxxxxx')`

**Comment by dreambe** [comment]
because my application don't support 'ping' command,
