### ISSUE TITLE
"TypeError: cannot unpack non-iterable NoneType object" when attempting to XCLAIM a stream message that no longer exists

### ISSUE THREAD

**Issue by zackelan** [aio-libs/aioredis#639]
This is a tricky edge case, so I'll give a repro example using redis-cli, then show how to provoke it in aioredis.

Create a stream and write some messages to it:

```
127.0.0.1:6379> xadd mystream '*' x 1
"1569004125994-0"
127.0.0.1:6379> xadd mystream '*' x 2
"1569004127018-0"
127.0.0.1:6379> xadd mystream '*' x 3
"1569004127826-0"
127.0.0.1:6379>
```

Create a consumer group, and read from the stream using that group:

```
127.0.0.1:6379> xgroup create mystream mygroup 0-0
OK
127.0.0.1:6379> xreadgroup group mygroup consumer1 count 10 streams mystream >
1) 1) "mystream"
   2) 1) 1) "1569004125994-0"
         2) 1) "x"
            2) "1"
      2) 1) "1569004127018-0"
         2) 1) "x"
            2) "2"
      3) 1) "1569004127826-0"
         2) 1) "x"
            2) "3"
```

As expected, that consumer has 3 pending messages:

```
127.0.0.1:6379> xinfo consumers mystream mygroup
1) 1) "name"
   2) "consumer1"
   3) "pending"
   4) (integer) 3
   5) "idle"
   6) (integer) 21656
```

Now, write 1000 messages to the stream, using a MAXLEN of 100. This is the crucial part of the bug - we're writing enough messages that those 3 entries that are currently pending will fall off the end of the stream.

```
$ for i in $(seq 1000); do redis-cli xadd mystream MAXLEN '~' 100 '*' x $i; done
```

As expected, the stream has about 100 items, and those 3 messages are still pending:

```
127.0.0.1:6379> xlen mystream
(integer) 195
127.0.0.1:6379> xpending mystream mygroup - + 10 consumer1
1) 1) "1569004125994-0"
   2) "consumer1"
   3) (integer) 253409
   4) (integer) 1
2) 1) "1569004127018-0"
   2) "consumer1"
   3) (integer) 253409
   4) (integer) 1
3) 1) "1569004127826-0"
   2) "consumer1"
   3) (integer) 253409
   4) (integer) 1
```

If a new consumer comes along and tries to XCLAIM them, Redis returns nil because those message IDs are no longer in the stream:

```
127.0.0.1:6379> xclaim mystream mygroup consumer2 1000 "1569004125994-0" "1569004127018-0" "1569004127826-0"
1) (nil)
2) (nil)
3) (nil)
```

Here's that same sequence of events using aioredis:

```
import asyncio
import secrets

import aioredis

STREAM = secrets.token_hex(8)
GROUP = 'mygroup'
CONSUMER = 'myconsumer'

async def main():
    conn = await aioredis.create_redis('redis://localhost')

    for i in range(3):
        await conn.xadd(STREAM, {'x': str(i)})

    await conn.xgroup_create(STREAM, GROUP, '0-0')

    messages = await conn.xread_group(GROUP, CONSUMER, [STREAM], count=10, latest_ids=['>'])
    print(f'messages: {messages}')

    for i in range(1000):
        await conn.xadd(STREAM, {'x': str(i)}, max_len=100)

    pending = await conn.xpending(STREAM, GROUP, '-', '+', 10, CONSUMER)
    print(f'pending: {pending}')

    message_ids = [message_id for message_id, consumer, idle_time, delivery_count in pending]
    print(f'claiming: {message_ids}')
    await conn.xclaim(STREAM, GROUP, 'new-consumer', 1, *message_ids)


if __name__ == '__main__':
    asyncio.run(main())
```

Results:

```
messages: [(b'1fb48fc917ab9bb0', b'1569011272493-0', OrderedDict([(b'x', b'0')])), (b'1fb48fc917ab9bb0', b'1569011272494-0', OrderedDict([(b'x', b'1')])), (b'1fb48fc917ab9bb0', b'1569011272494-1', OrderedDict([(b'x', b'2')]))]
pending: [[b'1569011272493-0', b'myconsumer', 154, 1], [b'1569011272494-0', b'myconsumer', 154, 1], [b'1569011272494-1', b'myconsumer', 154, 1]]
claiming: [b'1569011272493-0', b'1569011272494-0', b'1569011272494-1']
Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    asyncio.run(main())
  File "/nix/store/96p42644i76jqgdkxjgyl3f0c8n8k16j-python3-3.7.4/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/96p42644i76jqgdkxjgyl3f0c8n8k16j-python3-3.7.4/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "demo.py", line 29, in main
    await conn.xclaim(STREAM, GROUP, 'new-consumer', 1, *message_ids)
  File "/home/zack/.venv/lib/python3.7/site-packages/aioredis/util.py", line 58, in wait_convert
    return type_(result, **kwargs)
  File "/home/zack/.venv/lib/python3.7/site-packages/aioredis/commands/streams.py", line 36, in parse_messages
    return [(mid, fields_to_dict(values)) for mid, values in messages]
  File "/home/zack/.venv/lib/python3.7/site-packages/aioredis/commands/streams.py", line 36, in <listcomp>
    return [(mid, fields_to_dict(values)) for mid, values in messages]
TypeError: cannot unpack non-iterable NoneType object
```

Expected results:

I think this should return a (message_id, None) tuple for each of the messages this occurs with, and then I can special-case that None response to indicate that message no longer exists, and proceed with the rest of the process of cleaning up after that consumer.

Environment (though I don't think it matters for this) is Python 3.7.4, aioredis 1.2.0, hiredis 1.0.0, and Redis 5.0.4.

**Comment by popravich** [comment]
Resolved by #605. Released v1.3.0
