### ISSUE TITLE
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by HuangChangHuai** [aio-libs/aioredis#782]
```shell
HTTP GET /chat/123/ 200 [0.01, 127.0.0.1:60918]
WebSocket HANDSHAKING /ws/chat/123/ [127.0.0.1:60930]
WebSocket CONNECT /ws/chat/123/ [127.0.0.1:60930]
Exception inside application: ERR unknown command 'BZPOPMIN'
Traceback (most recent call last):
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\sessions.py", line 183, in __call__
    return await self.inner(receive, self.send)
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\utils.py", line 58, in await_many_dispatch
    await task
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 452, in receive
    message_channel, message = await self.receive_single(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 507, in receive_single
    content = await self._brpop_with_clean(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 345, in _brpop_with_clean
    result = await connection.bzpopmin(channel, timeout=timeout)
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'
WebSocket DISCONNECT /ws/chat/123/ [127.0.0.1:60930]

```

**Comment by anxolerd** [comment]
Hi.

From what I found searching around the web, `BZPOPMIN` command [is available since redis 5.0.0](https://redis.io/commands/bzpopmin). I believe you have an older version of redis, which does not support `BZPOPMIN` command.

I have also found [StackOverflow thread](https://stackoverflow.com/questions/62786988/redis-err-unknown-command-bzpopmin) with similar problem concerning Windows operating system (which is according to paths in your traceback) is exactly your case. It looks like, redis is not supported for Windows :(

You can try running redis in docker containers on windows, or using virtual machine with redis or try using windows subsystem for linux to run recent redis version. Unfortunately I am not a huge specialist on windows as neither am I maintainer of the lib.

Hope, my answer is helpful.

**Comment by HuangChangHuai** [comment]
thanks. because I'm a novice, inexperienced, I can't find the answer on the web, so I can only try to get help here, I do't know whether it is reasonable to do so
Your answer gave me a good solution,
thanks

**Comment by Nirav-Madhani** [comment]
I think this 2 answers will solve your problem:
https://stackoverflow.com/a/63291700/12907462
https://stackoverflow.com/a/65126159/12907462

Summary of above answers:
You need to install redis 5+
which can we found at link: https://github.com/tporadowski/redis/releases
